repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2  # Specify the correct version of ruff here
    hooks:
      - id: ruff
        args: ['--fix']  # Automatically fix code formatting issues

